name: Generate Python SBOM & Security Scan

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install CycloneDX
        run: pip install cyclonedx-bom

      - name: Generate SBOM
        run: cyclonedx-py requirements -i requirements.txt -o bom.json

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Scan for vulnerabilities and generate report
        run: pip-audit -r requirements.txt --format json -o report.json
        continue-on-error: true

      # - name: Fail on high severity vulnerabilities
      #   run: |
      #     python - <<'EOF'
      #     import json, sys
      #     with open('report.json') as f:
      #         data = json.load(f)
      #     high_vulns = [v for v in data if v.get('severity') in ['HIGH', 'CRITICAL']]
      #     if high_vulns:
      #         print("High severity vulnerabilities found!")
      #         for v in high_vulns:
      #             print(f"{v['name']}=={v['version']} : {v['id']} ({v['severity']})")
      #         sys.exit(1)
      #     EOF

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-file
          path: bom.json

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: report.json